[tool.poetry]
name = "dynamic-prediction-equilibria"
version = "0.1.0"
description = ""
authors = ["Michael Markl <marklmichael98@gmail.com>"]
readme = "README.md"
packages = [{include = "dynamic_prediction_equilibria"}]

[tool.poetry.dependencies]
python = "3.11.2"
tensorflow = "^2.12.1"
torch = "^2.0.1"
click = "^8.1.3"
pylint = "^2.15.5"
matplotlib = "^3.6.2"
numpy = "^1.23.4"
autopep8 = "^2.0.0"
scikit-learn = "^1.1.3"
pandas = "^1.5.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
